/**
 * After a local deployment, this script reads the deployed contract address
 * from Hardhat Ignition's output and writes it to front-end/.env.local so
 * the React app picks it up automatically on the next `npm start`.
 */
import { readFileSync, writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

const deployedPath = resolve(
  __dirname,
  "../ignition/deployments/chain-31337/deployed_addresses.json"
);

let addresses;
try {
  addresses = JSON.parse(readFileSync(deployedPath, "utf8"));
} catch {
  console.error("Could not read deployed_addresses.json — did you run deploy:local first?");
  process.exit(1);
}

const address = addresses["SupplyChainProvenanceModule#SupplyChainProvenance"];
if (!address) {
  console.error("Contract address not found in deployed_addresses.json");
  process.exit(1);
}

const envPath = resolve(__dirname, "../../front-end/.env.local");
const envContent = `# Auto-generated by scripts/sync-local.js — do not edit manually
REACT_APP_CONTRACT_ADDRESS=${address}
REACT_APP_RPC_URL=http://127.0.0.1:8545
`;

writeFileSync(envPath, envContent);
console.log(`Updated front-end/.env.local`);
console.log(`  REACT_APP_CONTRACT_ADDRESS=${address}`);
console.log(`  REACT_APP_RPC_URL=http://127.0.0.1:8545`);
